export type Project = {
  slug: string;
  title: string;
  platform: string;
  category: string;
  summary: string;
  detailSummary?: string[];
  tech: string[];
  role: string;
  outcome: string;
  liveUrl?: string;
  githubUrl?: string;
  awardUrl?: string;
  awardLabel?: string;
  videoUrl?: string;
  videoLabel?: string;
  featureVideo?: string;
  featureVideoLabel?: string;
  image?: string;
};